#python script_testing.py --model "AHDR" --run_name "org"
#python script_testing.py --model "AHDR" --epoch "250"
#python script_testing.py --model "AHDR" --epoch "500"
#python script_testing.py --model "AHDR" --epoch "750"
#python script_testing.py --model "AHDR" --epoch "1000"
#python script_testing.py --model "AHDR" --run_name "mono_f64" --format "mono" --nChannel 2 --nFeat 64 --epoch "250"
#python script_testing.py --model "AHDR" --run_name "mono_f64" --format "mono" --nChannel 2 --nFeat 64 --epoch "500"
#python script_testing.py --model "AHDR" --run_name "mono_f64" --format "mono" --nChannel 2 --nFeat 64 --epoch "750"
#python script_testing.py --model "AHDR" --run_name "mono_f64" --format "mono" --nChannel 2 --nFeat 64 --epoch "1000"
#python script_testing.py --model "AHDR" --run_name "mono_f16" --format "mono" --nChannel 2 --nFeat 16 --epoch "250"
#python script_testing.py --model "AHDR" --run_name "mono_f16" --format "mono" --nChannel 2 --nFeat 16 --epoch "500"
#python script_testing.py --model "AHDR" --run_name "mono_f16" --format "mono" --nChannel 2 --nFeat 16 --epoch "750"
#python script_testing.py --model "AHDR" --run_name "mono_f16" --format "mono" --nChannel 2 --nFeat 16 --epoch "1000"
#python script_testing.py --model "AHDR" --run_name "ddp_test" --epoch "1100"
#python script_testing.py --model "AHDR" --run_name "yuv444" --format "444" --epoch "250"
#python script_testing.py --model "AHDR" --run_name "yuv444" --format "444" --epoch "500"
#python script_testing.py --model "AHDR" --run_name "yuv444" --format "444" --epoch "750"
#python script_testing.py --model "AHDR" --run_name "yuv444" --format "444" --epoch "1000"
#python script_testing_ch.py --model "AHDR" --run_name "chRGB" --format "rgb" --nChannel 2 --epoch "250"
#python script_testing.py --model "LIGHTFUSE" --epoch 70 --run_name "ref_only_bk" --format "rgb_dual" --nChannel 3 --nFeat 32
python script_testing.py --model "LIGHTFUSE" --epoch 90 --run_name "dual-vgg_loss" --format "rgb_dual" --nChannel 6 --nFeat 32
